from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field, HttpUrl


class ApplicationStatus(str, Enum):
    DISCOVERED = "discovered"
    MATCHED = "matched"
    REJECTED_LOW_SCORE = "rejected_low_score"
    APPROVED = "approved"
    APPLIED = "applied"
    INTERVIEWING = "interviewing"
    OFFER = "offer"


class MatchEvaluation(BaseModel):
    """Detailed evaluation score generated by the Matcher Agent."""
    match_score: float = Field(..., ge=0.0, le=100.0, description="Overall match percentage")
    matching_skills: List[str] = Field(default_factory=list, description="Skills present in candidate profile")
    missing_skills: List[str] = Field(default_factory=list, description="Key skills requested but missing")
    strengths: List[str] = Field(default_factory=list, description="Specific profile advantages for this role")
    skill_gaps: List[str] = Field(default_factory=list, description="Areas where candidate falls short")
    reasoning: str = Field(..., description="LLM explanation for the assigned match score")
    should_apply: bool = Field(..., description="True if score >= user's threshold")


class InternshipListing(BaseModel):
    """Standardized job posting extracted from career sites or search results."""
    # Source Metadata
    canonical_url: HttpUrl = Field(..., description="Direct application page URL")
    source_platform: str = Field(..., description="Origin site (e.g., 'Greenhouse', 'Lever', 'LinkedIn')")
    
    # Role Metadata
    title: str = Field(..., description="Role title (e.g., 'Software Engineering Intern - Summer 2026')")
    company_name: str = Field(..., description="Hiring company name")
    location: str = Field(..., description="Office location or Remote status")
    work_type: str = Field(default="Unknown", description="Remote, Hybrid, or On-site")
    
    # Job Content
    raw_description: str = Field(..., description="Full cleaned textual content of the posting")
    required_skills: List[str] = Field(default_factory=list, description="Mandatory tech/domain skills")
    preferred_skills: List[str] = Field(default_factory=list, description="Nice-to-have qualifications")
    stipend_info: Optional[str] = Field(None, description="Compensation details if specified")
    
    # Dates & Timestamps
    date_posted: Optional[str] = Field(None, description="Date role was published if available")
    deadline: Optional[str] = Field(None, description="Application submission deadline")
    extracted_at: datetime = Field(default_factory=datetime.utcnow, description="System ingestion timestamp")
    
    # Pipeline Processing State
    status: ApplicationStatus = Field(default=ApplicationStatus.DISCOVERED, description="Tracking state")
    evaluation: Optional[MatchEvaluation] = Field(None, description="Matcher Agent analysis if computed")

    model_config = ConfigDict(
        use_enum_values=True,
        json_encoders={datetime: lambda v: v.isoformat()}
    )